"""Qualification catalog: sectors, qualifications and competencies.

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 16:10:24.028960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may emit sqlmodel.sql.sqltypes types)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sector')),
    sa.UniqueConstraint('name', name=op.f('uq_sector_name'))
    )
    op.create_table('qualification',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('skill_label', sa.String(length=120), nullable=False),
    sa.Column('career_keywords', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('possible_jobs', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name=op.f('fk_qualification_sector_id_sector'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualification')),
    sa.UniqueConstraint('code', name=op.f('uq_qualification_code'))
    )
    op.create_index(op.f('ix_qualification_sector_id'), 'qualification', ['sector_id'], unique=False)
    op.create_table('competency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('Basic', 'Common', 'Core')", name=op.f('ck_competency_category_valid')),
    sa.CheckConstraint('position > 0', name=op.f('ck_competency_position_positive')),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_competency_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency')),
    sa.UniqueConstraint('qualification_id', 'position', name='uq_competency_qualification_position')
    )
    op.create_index(op.f('ix_competency_qualification_id'), 'competency', ['qualification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competency_qualification_id'), table_name='competency')
    op.drop_table('competency')
    op.drop_index(op.f('ix_qualification_sector_id'), table_name='qualification')
    op.drop_table('qualification')
    op.drop_table('sector')
    # ### end Alembic commands ###
