"""Learner accounts, goals, recommendation sessions, readiness checks and certifications.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 16:28:03.020674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may emit sqlmodel.sql.sqltypes types)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('privacy_consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('learner', 'admin')", name=op.f('ck_learner_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner')),
    sa.UniqueConstraint('email', name=op.f('uq_learner_email'))
    )
    op.create_table('certification',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_body', sa.String(length=150), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.CheckConstraint("source IN ('self_reported', 'assessment')", name=op.f('ck_certification_source_valid')),
    sa.CheckConstraint('expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on', name=op.f('ck_certification_dates_ordered')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_certification_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_certification_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certification'))
    )
    op.create_index(op.f('ix_certification_learner_id'), 'certification', ['learner_id'], unique=False)
    op.create_table('goal',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('target_qualification_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'achieved', 'archived')", name=op.f('ck_goal_status_valid')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_goal_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_qualification_id'], ['qualification.id'], name=op.f('fk_goal_target_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal'))
    )
    op.create_index(op.f('ix_goal_learner_id'), 'goal', ['learner_id'], unique=False)
    op.create_table('recommendation_session',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('analysis_source', sa.String(length=10), nullable=False),
    sa.Column('analysis_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.Column('pathway', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("analysis_source IN ('rules', 'ai')", name=op.f('ck_recommendation_session_analysis_source_valid')),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], name=op.f('fk_recommendation_session_goal_id_goal'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_recommendation_session_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_recommendation_session_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_session'))
    )
    op.create_index(op.f('ix_recommendation_session_learner_id'), 'recommendation_session', ['learner_id'], unique=False)
    op.create_table('readiness_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_session_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_readiness_check_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_readiness_check_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_session_id'], ['recommendation_session.id'], name=op.f('fk_readiness_check_recommendation_session_id_recommendation_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_check'))
    )
    op.create_index(op.f('ix_readiness_check_learner_id'), 'readiness_check', ['learner_id'], unique=False)
    op.create_index(op.f('ix_readiness_check_qualification_id'), 'readiness_check', ['qualification_id'], unique=False)
    op.create_table('readiness_answer',
    sa.Column('readiness_check_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.CheckConstraint("answer IN ('confident', 'some_experience', 'not_familiar')", name=op.f('ck_readiness_answer_answer_valid')),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], name=op.f('fk_readiness_answer_competency_id_competency'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['readiness_check_id'], ['readiness_check.id'], name=op.f('fk_readiness_answer_readiness_check_id_readiness_check'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('readiness_check_id', 'competency_id', name=op.f('pk_readiness_answer'))
    )
    op.create_index(op.f('ix_readiness_answer_competency_id'), 'readiness_answer', ['competency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readiness_answer_competency_id'), table_name='readiness_answer')
    op.drop_table('readiness_answer')
    op.drop_index(op.f('ix_readiness_check_qualification_id'), table_name='readiness_check')
    op.drop_index(op.f('ix_readiness_check_learner_id'), table_name='readiness_check')
    op.drop_table('readiness_check')
    op.drop_index(op.f('ix_recommendation_session_learner_id'), table_name='recommendation_session')
    op.drop_table('recommendation_session')
    op.drop_index(op.f('ix_goal_learner_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_certification_learner_id'), table_name='certification')
    op.drop_table('certification')
    op.drop_table('learner')
    # ### end Alembic commands ###
