"""Regions, training providers and programs, assessment centers/schedules/applications, pathways.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 22:01:22.793301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may emit sqlmodel.sql.sqltypes types)


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Must match tesda_track.services.geo.point() so distance searches can use these indexes.
LOCATION_INDEXES = {
    "ix_training_provider_location_gist": "training_provider",
    "ix_assessment_center_location_gist": "assessment_center",
}


def upgrade() -> None:
    """Upgrade schema."""
    # No-op when the database image already installed PostGIS; otherwise needs a privileged role.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('center_city', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_region'))
    )
    op.create_table('assessment_center',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_training_provider_location_complete')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_training_provider_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_training_provider_longitude_range')),
    sa.ForeignKeyConstraint(['region_code'], ['region.code'], name=op.f('fk_assessment_center_region_code_region'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_center'))
    )
    op.create_index(op.f('ix_assessment_center_region_code'), 'assessment_center', ['region_code'], unique=False)
    op.create_table('training_provider',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_training_provider_location_complete')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_training_provider_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_training_provider_longitude_range')),
    sa.ForeignKeyConstraint(['region_code'], ['region.code'], name=op.f('fk_training_provider_region_code_region'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_provider'))
    )
    op.create_index(op.f('ix_training_provider_region_code'), 'training_provider', ['region_code'], unique=False)
    op.create_table('assessment_schedule',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed', 'cancelled', 'completed')", name=op.f('ck_assessment_schedule_status_valid')),
    sa.CheckConstraint('fee IS NULL OR fee >= 0', name=op.f('ck_assessment_schedule_fee_not_negative')),
    sa.CheckConstraint('slots > 0', name=op.f('ck_assessment_schedule_slots_positive')),
    sa.ForeignKeyConstraint(['center_id'], ['assessment_center.id'], name=op.f('fk_assessment_schedule_center_id_assessment_center'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_assessment_schedule_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_schedule'))
    )
    op.create_index(op.f('ix_assessment_schedule_center_id'), 'assessment_schedule', ['center_id'], unique=False)
    op.create_index(op.f('ix_assessment_schedule_qualification_id'), 'assessment_schedule', ['qualification_id'], unique=False)
    op.create_index(op.f('ix_assessment_schedule_scheduled_at'), 'assessment_schedule', ['scheduled_at'], unique=False)
    op.create_table('pathway',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("route IN ('TRAINING_AND_ASSESSMENT', 'ASSESSMENT_READINESS', 'SKILL_GAP_CHECK')", name=op.f('ck_pathway_route_valid')),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_pathway_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathway')),
    sa.UniqueConstraint('qualification_id', 'route', name='uq_pathway_qualification_route')
    )
    op.create_index(op.f('ix_pathway_qualification_id'), 'pathway', ['qualification_id'], unique=False)
    op.create_table('training_program',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=30), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scholarship_available', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("delivery_mode IN ('institution_based', 'enterprise_based', 'community_based', 'online')", name=op.f('ck_training_program_delivery_mode_valid')),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name=op.f('ck_training_program_cost_not_negative')),
    sa.CheckConstraint('duration_hours IS NULL OR duration_hours > 0', name=op.f('ck_training_program_duration_positive')),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_training_program_dates_ordered')),
    sa.CheckConstraint('slots IS NULL OR slots > 0', name=op.f('ck_training_program_slots_positive')),
    sa.ForeignKeyConstraint(['provider_id'], ['training_provider.id'], name=op.f('fk_training_program_provider_id_training_provider'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_training_program_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_program'))
    )
    op.create_index(op.f('ix_training_program_provider_id'), 'training_program', ['provider_id'], unique=False)
    op.create_index(op.f('ix_training_program_qualification_id'), 'training_program', ['qualification_id'], unique=False)
    op.create_table('assessment_application',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('reviewer_note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("result IS NULL OR result IN ('competent', 'not_yet_competent')", name=op.f('ck_assessment_application_result_valid')),
    sa.CheckConstraint("result IS NULL OR status = 'completed'", name=op.f('ck_assessment_application_result_only_when_completed')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'withdrawn', 'completed')", name=op.f('ck_assessment_application_status_valid')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_assessment_application_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['assessment_schedule.id'], name=op.f('fk_assessment_application_schedule_id_assessment_schedule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_application')),
    sa.UniqueConstraint('learner_id', 'schedule_id', name='uq_assessment_application_learner_schedule')
    )
    op.create_index(op.f('ix_assessment_application_learner_id'), 'assessment_application', ['learner_id'], unique=False)
    op.create_index(op.f('ix_assessment_application_schedule_id'), 'assessment_application', ['schedule_id'], unique=False)
    op.create_table('pathway_enrollment',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'withdrawn')", name=op.f('ck_pathway_enrollment_status_valid')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_pathway_enrollment_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathway.id'], name=op.f('fk_pathway_enrollment_pathway_id_pathway'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathway_enrollment')),
    sa.UniqueConstraint('learner_id', 'pathway_id', name='uq_pathway_enrollment_learner_pathway')
    )
    op.create_index(op.f('ix_pathway_enrollment_learner_id'), 'pathway_enrollment', ['learner_id'], unique=False)
    op.create_index(op.f('ix_pathway_enrollment_pathway_id'), 'pathway_enrollment', ['pathway_id'], unique=False)
    op.create_table('pathway_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('self_check', 'training', 'assessment', 'certification', 'other')", name=op.f('ck_pathway_step_kind_valid')),
    sa.CheckConstraint('position > 0', name=op.f('ck_pathway_step_position_positive')),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathway.id'], name=op.f('fk_pathway_step_pathway_id_pathway'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathway_step')),
    sa.UniqueConstraint('pathway_id', 'position', deferrable=True, initially='DEFERRED', name='uq_pathway_step_pathway_position')
    )
    op.create_index(op.f('ix_pathway_step_pathway_id'), 'pathway_step', ['pathway_id'], unique=False)
    op.create_table('step_progress',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed')", name=op.f('ck_step_progress_status_valid')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['pathway_enrollment.id'], name=op.f('fk_step_progress_enrollment_id_pathway_enrollment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['pathway_step.id'], name=op.f('fk_step_progress_step_id_pathway_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id', 'step_id', name=op.f('pk_step_progress'))
    )
    op.add_column('certification', sa.Column('assessment_application_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_certification_assessment_application_id'), 'certification', ['assessment_application_id'])
    op.create_foreign_key(op.f('fk_certification_assessment_application_id_assessment_application'), 'certification', 'assessment_application', ['assessment_application_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    for index, table in LOCATION_INDEXES.items():
        op.execute(f"CREATE INDEX {index} ON {table} "
                   "USING gist (geography(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)))")


def downgrade() -> None:
    """Downgrade schema."""
    for index in LOCATION_INDEXES:
        op.execute(f"DROP INDEX IF EXISTS {index}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_certification_assessment_application_id_assessment_application'), 'certification', type_='foreignkey')
    op.drop_constraint(op.f('uq_certification_assessment_application_id'), 'certification', type_='unique')
    op.drop_column('certification', 'assessment_application_id')
    op.drop_table('step_progress')
    op.drop_index(op.f('ix_pathway_step_pathway_id'), table_name='pathway_step')
    op.drop_table('pathway_step')
    op.drop_index(op.f('ix_pathway_enrollment_pathway_id'), table_name='pathway_enrollment')
    op.drop_index(op.f('ix_pathway_enrollment_learner_id'), table_name='pathway_enrollment')
    op.drop_table('pathway_enrollment')
    op.drop_index(op.f('ix_assessment_application_schedule_id'), table_name='assessment_application')
    op.drop_index(op.f('ix_assessment_application_learner_id'), table_name='assessment_application')
    op.drop_table('assessment_application')
    op.drop_index(op.f('ix_training_program_qualification_id'), table_name='training_program')
    op.drop_index(op.f('ix_training_program_provider_id'), table_name='training_program')
    op.drop_table('training_program')
    op.drop_index(op.f('ix_pathway_qualification_id'), table_name='pathway')
    op.drop_table('pathway')
    op.drop_index(op.f('ix_assessment_schedule_scheduled_at'), table_name='assessment_schedule')
    op.drop_index(op.f('ix_assessment_schedule_qualification_id'), table_name='assessment_schedule')
    op.drop_index(op.f('ix_assessment_schedule_center_id'), table_name='assessment_schedule')
    op.drop_table('assessment_schedule')
    op.drop_index(op.f('ix_training_provider_region_code'), table_name='training_provider')
    op.drop_table('training_provider')
    op.drop_index(op.f('ix_assessment_center_region_code'), table_name='assessment_center')
    op.drop_table('assessment_center')
    op.drop_table('region')
    # ### end Alembic commands ###
