"""Embeddings for semantic search (pgvector), the ranking audit trail, and the TTL cache.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 22:39:23.347883

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401  (vector column type)
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate may emit sqlmodel.sql.sqltypes types)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # No-op when the database image already installed pgvector; otherwise needs a privileged role.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entry',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_cache_entry'))
    )
    op.create_index(op.f('ix_cache_entry_expires_at'), 'cache_entry', ['expires_at'], unique=False)
    op.create_table('qualification_embedding',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_qualification_embedding_qualification_id_qualification'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qualification_id', name=op.f('pk_qualification_embedding'))
    )
    op.create_table('ranking_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=True),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('near_lat', sa.Float(), nullable=True),
    sa.Column('near_lon', sa.Float(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_ranking_audit_learner_id_learner'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], name=op.f('fk_ranking_audit_qualification_id_qualification'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_audit'))
    )
    op.create_index(op.f('ix_ranking_audit_learner_id'), 'ranking_audit', ['learner_id'], unique=False)
    op.create_index(op.f('ix_ranking_audit_qualification_id'), 'ranking_audit', ['qualification_id'], unique=False)
    op.create_table('training_program_embedding',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['training_program.id'], name=op.f('fk_training_program_embedding_program_id_training_program'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', name=op.f('pk_training_program_embedding'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_program_embedding')
    op.drop_index(op.f('ix_ranking_audit_qualification_id'), table_name='ranking_audit')
    op.drop_index(op.f('ix_ranking_audit_learner_id'), table_name='ranking_audit')
    op.drop_table('ranking_audit')
    op.drop_table('qualification_embedding')
    op.drop_index(op.f('ix_cache_entry_expires_at'), table_name='cache_entry')
    op.drop_table('cache_entry')
    # ### end Alembic commands ###
